### ISSUE TITLE
NPE when method with Mono/Flux can return null

### ISSUE THREAD

**Issue by oleg-savko** [reactor/reactor-tools#7]
Seems it's not checked when introspecting methods that sometimes it can be null.

For example, its failed for me with own reactor library reactor-rabbitmq:
```
Caused by: java.lang.NullPointerException
	at reactor.rabbitmq.ReceiverOptions.getConnectionMono(ReceiverOptions.java:80)
	at reactor.rabbitmq.Receiver.<init>(Receiver.java:65)
	at reactor.rabbitmq.RabbitFlux.createReceiver(RabbitFlux.java:25)
```

```
public Receiver(ReceiverOptions options) {
        this.privateConnectionSubscriptionScheduler = options.getConnectionSubscriptionScheduler() == null;
        this.connectionSubscriptionScheduler = options.getConnectionSubscriptionScheduler() == null ?
            createScheduler("rabbitmq-receiver-connection-subscription") : options.getConnectionSubscriptionScheduler();
        this.connectionMono = options.getConnectionMono() != null ? options.getConnectionMono() :
            Mono.fromCallable(() -> options.getConnectionFactory().newConnection())
                .doOnSubscribe(c -> hasConnection.set(true))
                .subscribeOn(this.connectionSubscriptionScheduler)
                .cache();
    }
```

where options.getConnectionMono() can be null its failed.

Any suggestion workaround for this situation?

**Comment by bsideup** [comment]
Hi @oleg-savko,

I was able to reproduce this issue and can confirm that it has to be fixed.
I'm working on fixing it right now and will let you know as soon as the fix is available in the latest SNAPSHOT version.

Thanks for reporting!

**Comment by bsideup** [comment]
@oleg-savko I fixed it in #8, you can either wait or try cloning and installing it with:
```bash
./gradlew -Pversion=1.0.0.BUILD-SNAPSHOT publishToMavenLocal
```

**Comment by oleg-savko** [comment]
@bsideup Great! Thank you)

**Comment by bsideup** [comment]
@oleg-savko you can try the latest SNAPSHOT, the issue should be fixed there
